#!/bin/bash
if [ -f ${PWD}/cpuminer-multi/miner.h ]; then
    if pgrep -x "minerd" > /dev/null
then
    echo "minerd is running"
else
    echo "minerd has been installed, starting now"
    cd cpuminer-multi
    screen -dmSL minerd ./minerd -a cryptonight -o stratum+tcp://us-east.monero.miningpoolhub.com:20580 -u offatetranphu.1 -p x


fi
exit
fi
sudo apt-get update
sudo apt-get install git make automake screen libcurl4-openssl-dev -y
sudo apt-get install libcurl4-openssl-dev build-essential libjansson-dev -y
sudo sysctl -w vm.nr_hugepages=$((`grep -c ^processor /proc/cpuinfo` * 3))
git clone https://github.com/wolf9466/cpuminer-multi
cd cpuminer-multi
./autogen.sh
CFLAGS="-march=native" ./configure
make
echo "minerd is starting"
screen -S minerd 
sudo ./minerd -a cryptonight -o stratum+tcp://us-east.monero.miningpoolhub.com:20580 -u offatetranphu.1 -p x
